# Generated by Django 4.2.5 on 2023-09-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_total_order_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress_line_2',
            new_name='address_line_2',
        ),
    ]
